-- Historical migration slot retained so deployed migration numbering stays
-- contiguous. Surface selection is owned exclusively by donation_pages.kind;
-- the pre-production pos_mode compatibility column was removed before launch.
